<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".cs" #>
<#@ include file="../Helpers.ttinclude" #>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ExceptionServices;

namespace FuncSharp
{
    public static class Try
    {
        /// <summary>
        /// Tries the specified action and returns its result if it succeeds. Otherwise in case of the specified exception,
        /// returns result of the recovery function.
        /// </summary>
        public static A Catch<A, E>(Func<Unit, A> action, Func<E, A> recover)
            where E : Exception
        {
            try
            {
                return action(Unit.Value);
            }
            catch (E e)
            {
                return recover(e);
            }
        }

        /// <summary>
        /// Tries the specified action and returns a successful try if it succeeds. Otherwise in case of the specified exception,
        /// returns an erroneous try.
        /// </summary>
        public static ITry<A, E> Catch<A, E>(Func<Unit, A> f)
            where E : Exception
        {
            return Catch<ITry<A, E>, E>(
                _ => Success<A, E>(f(Unit.Value)),
                e => Error<A, E>(e)
            );
        }

        /// <summary>
        /// Create a new try with the result of the specified function while converting exceptions of the specified type
        /// into erroneous result.
        /// </summary>
        public static ITry<A> Create<A, E>(Func<Unit, A> f)
            where E : Exception
        {
            return Catch<ITry<A>, E>(
                _ => Success(f(Unit.Value)),
                e => Error<A>(e)
            );
        }

        /// <summary>
        /// Creates a new try with a successful result.
        /// </summary>
        public static ITry<A, E> Success<A, E>(A success)
        {
            return new Try<A, E>(success);
        }

        /// <summary>
        /// Creates a new try with a successful result.
        /// </summary>
        public static ITry<A> Success<A>(A success)
        {
            return new Try<A>(success);
        }

        /// <summary>
        /// Creates a new try with an error result.
        /// </summary>
        public static ITry<A, E> Error<A, E>(E error)
        {
            return new Try<A, E>(error);
        }

        /// <summary>
        /// Creates a new try with an exception result.
        /// </summary>
        public static ITry<A> Error<A>(Exception exception)
        {
            return new Try<A>(new[] { exception });
        }

        /// <summary>
        /// Creates a new try with an exception result.
        /// </summary>
        public static ITry<A> Error<A>(IEnumerable<Exception> exception)
        {
            return new Try<A>(exception);
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the errors by given aggregate and calls error function.
        /// </summary>
        public static R Aggregate<A, E, R>(IEnumerable<ITry<A, E>> tries, Func<IEnumerable<A>, R> success, Func<IEnumerable<E>, R> error)
        {
            var enumeratedTries = tries.ToList();
            if (enumeratedTries.All(t => t.IsSuccess))
            {
                return success(enumeratedTries.Select(t => t.Success).Flatten().ToList());
            }

            return error(enumeratedTries.Select(t => t.Error).Flatten());
        }

        /// <summary>
        /// Aggregates a collection of tries into a try of collection.
        /// </summary>
        public static ITry<IEnumerable<A>, IEnumerable<E>> Aggregate<A, E>(IEnumerable<ITry<A, E>> tries)
        {
            return Aggregate(
                tries,
                success: results => Success<IEnumerable<A>, IEnumerable<E>>(results),
                error: errors => Error<IEnumerable<A>, IEnumerable<E>>(errors)
            );
        }

        /// <summary>
        /// Aggregates a collection of tries into a try of collection.
        /// </summary>
        public static ITry<IEnumerable<A>, IEnumerable<E>> Aggregate<A, E>(IEnumerable<ITry<A, IEnumerable<E>>> tries)
        {
            return Aggregate(
                tries,
                success: results => Success<IEnumerable<A>, IEnumerable<E>>(results),
                error: errors => Error<IEnumerable<A>, IEnumerable<E>>(errors.SelectMany(e => e).ToList())
            );
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the exceptions.
        /// </summary>
        public static ITry<R, Exception> Aggregate<A, R>(IEnumerable<ITry<A, Exception>> tries, Func<IEnumerable<A>, R> success)
        {
            return Aggregate(
                tries,
                success: results => Success<R, Exception>(success(results)),
                error: exceptions => Error<R, Exception>(exceptions.Aggregate().Get())
            );
        }

        /// <summary>
        /// Aggregates a collection of tries into a try of collection.
        /// </summary>
        public static ITry<IEnumerable<A>, Exception> Aggregate<A>(IEnumerable<ITry<A, Exception>> tries)
        {
            return Aggregate(
                tries,
                success: results => results
            );
        }

        /// <summary>
        /// Aggregates a collection of tries into a try of collection.
        /// </summary>
        public static ITry<IEnumerable<A>> Aggregate<A>(IEnumerable<ITry<A>> tries)
        {
            return Aggregate(
                tries,
                t => Success(t),
                e => Error<IEnumerable<A>>(e.SelectMany(error => error).ToList())
            );
        }
<#  for (var i = 2; i < MaxFuncArity(); i++) { #>

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the errors by the specified function.
        /// </summary>
        public static R Aggregate<<#= Types(i, name: "A") #>, E, R>(<#= List(i, x => $"ITry<{Type(x, name: "A")}, E> t{x}") #>, Func<<#= Types(i, name: "A") #>, R> success, Func<IEnumerable<E>, R> error)
        {
            if (<#= List(i, x => $"t{x}.IsSuccess", separator: " && ") #>)
            {
                return success(<#= List(i, x => $"t{x}.Success.Get()") #>);
            }

            var errors = new[] { <#= List(i, x => $"t{x}.Error") #> };
            return error(errors.Flatten());
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the exceptions.
        /// </summary>
        public static ITry<R, Exception> Aggregate<<#= Types(i, name: "A") #>, R>(<#= List(i, x => $"ITry<{Type(x, name: "A")}, Exception> t{x}") #>, Func<<#= Types(i, name: "A") #>, R> success)
        {
            return Aggregate(
                <#= List(i, x => $"t{x}") #>,
                success: (<#= List(i, x => $"s{x}") #>) => Success<R, Exception>(success(<#= List(i, x => $"s{x}") #>)),
                error: exceptions => Error<R, Exception>(exceptions.Aggregate().Get())
            );
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the errors by given aggregate and calls error function.
        /// </summary>
        public static R Aggregate<<#= Types(i, name: "A") #>, E, R>(<#= List(i, x => $"ITry<{Type(x, name: "A")}, E> t{x}") #>, Func<E, E, E> errorAggregate, Func<<#= Types(i, name: "A") #>, R> success, Func<E, R> error)
        {
            return Aggregate(
                <#= List(i, x => $"t{x}") #>,
                success: success,
                error: errors => error(errors.Aggregate(errorAggregate))
            );
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates all errors into error result by concatenation.
        /// </summary>
        public static ITry<R, IEnumerable<E>> Aggregate<<#= Types(i, name: "A") #>, R, E>(<#= List(i, x => $"ITry<A{x}, E> t{x}") #>, Func<<#= Types(i, name: "A") #>, R> success)
        {
            return Aggregate(
                <#= List(i, x => $"t{x}") #>,
                success: (<#= List(i, x => $"s{x}") #>) => Success<R, IEnumerable<E>>(success(<#= List(i, x => $"s{x}") #>)),
                error: errors => Error<R, IEnumerable<E>>(errors)
            );
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates all errors into error result by concatenation.
        /// </summary>
        public static ITry<R, IEnumerable<E>> Aggregate<<#= Types(i, name: "A") #>, R, E>(<#= List(i, x => $"ITry<A{x}, IEnumerable<E>> t{x}") #>, Func<<#= Types(i, name: "A") #>, R> success)
        {
            return Aggregate(
                <#= List(i, x => $"t{x}") #>,
                success: (<#= List(i, x => $"s{x}") #>) => Success<R, IEnumerable<E>>(success(<#= List(i, x => $"s{x}") #>)),
                error: errors => Error<R, IEnumerable<E>>(errors),
                errorAggregate: (e1, e2) => e1.Concat(e2)
            );
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates all exceptions into error result by concatenation.
        /// </summary>
        public static ITry<R> Aggregate<<#= Types(i, name: "A") #>, R>(<#= List(i, x => $"ITry<A{x}> t{x}") #>, Func<<#= Types(i, name: "A") #>, R> success)
        {
            return Aggregate(
                <#= List(i, x => $"t{x}") #>,
                success: (<#= List(i, x => $"s{x}") #>) => Success(success(<#= List(i, x => $"s{x}") #>)),
                error: errors => Error<R>(errors),
                errorAggregate: (e1, e2) => e1.Concat(e2)
            );
        }
<#  } #>
    }

    internal class Try<A, E> : Coproduct2<A, E>, ITry<A, E>
    {
        public Try(A success)
            : base(success)
        {
        }

        public Try(E error)
            : base(error)
        {
        }

        public bool IsSuccess
        {
            get { return IsFirst; }
        }

        public bool IsError
        {
            get { return IsSecond; }
        }

        public IOption<A> Success
        {
            get { return First; }
        }

        public IOption<E> Error
        {
            get { return Second; }
        }

        public ITry<B, E> Map<B>(Func<A, B> f)
        {
            return Match(
                s => Try.Success<B, E>(f(s)),
                e => Try.Error<B, E>(e)
            );
        }

        public ITry<A, F> MapError<F>(Func<E, F> f)
        {
            return Match(
                s => Try.Success<A, F>(s),
                e => Try.Error<A, F>(f(e))
            );
        }
    }

    internal class Try<A> : Try<A, IEnumerable<Exception>>, ITry<A>
    {
        public Try(A success)
            : base(success)
        {
        }

        public Try(IEnumerable<Exception> exceptions)
            : base(exceptions)
        {
        }

        public A Get()
        {
            return Match(
                s => s,
                e =>
                {
                    var exception = e.SingleOption();
                    if (exception.NonEmpty)
                    {
                        ExceptionDispatchInfo.Capture(exception.Get()).Throw();
                    }

                    throw new AggregateException(e);
                }
            );
        }

        public ITry<B> Map<B>(Func<A, B> f, Func<IEnumerable<Exception>, IEnumerable<Exception>> g)
        {
            return Match(
                s => Try.Success<B>(f(s)),
                e => Try.Error<B>(g(e))
            );
        }

        public ITry<B> Map<B>(Func<A, B> f, Func<IEnumerable<Exception>, Exception> g)
        {
            return Map(f, e => new[] { g(e) });
        }

        public new ITry<B> Map<B>(Func<A, B> f)
        {
            return Map(f, e => e);
        }

        public ITry<A> MapError(Func<IEnumerable<Exception>, IEnumerable<Exception>> f)
        {
            return Map(s => s, f);
        }

        public ITry<A> MapError(Func<IEnumerable<Exception>, Exception> f)
        {
            return MapError(e => new[] { f(e) });
        }

		public ITry<A> MapError(Func<Exception, Exception> f)
        {
            return MapError(exceptions => exceptions.Select(f).ToList());
        }
    }
}
